### ISSUE TITLE
lib contents are dead symlinks

### ISSUE THREAD

**Issue by carleeno** [Xinyuan-LilyGO/T-Touchbar-AMOLED#1]
When trying to get started with this example project, I was having build errors because lvgl and TouchLib were missing. It looks like they are symlinks.

I was eventually able to find the libraries and the correct lv config (I think)...but still wanted to shared in case you didn't realize they were missing.

**Comment by bezalel6** [comment]
still a problem

**Comment by makerwolf** [comment]
What I find worse than them just not being able to correctly implement submodules is the fact that they ignore github issues for more than a year, while they are pointing all support requests on the website to github. I'm losing my faith in this company completely. Cute hardware, but you are left alone.

**Comment by lewisxhe** [comment]
Fixed
